### ISSUE TITLE
Coverart

### ISSUE THREAD

**Issue by deathbybandaid** [arantius/zap2xml-py#1]
I forked your project, and I patched this to work for my needs. However, included in my quick patching is the channel logos and the coverart for programs. Feel free to duplicate this code.

I also am using this with nginx, and changed the output directory.

Additionally, I'm handling multiple zipcodes, so I have the filenames reflect the zipcodes.

https://github.com/deathbybandaid/zap2xml-py/blob/master/zap2xml.py

Side note, I paired this with the locast2plex project.

**Comment by arantius** [comment]
Thanks for your interest!  Excluding the art for individual episodes was part of the reason I decided to write my own version:  I *don't* want that, as Tvheadend tends to then accumulate them in tens of thousands of files, and hang for tens of seconds reading something about them all at launch.  Plus I never look at individual episodes' art, anyway.

I'm happy that both of us have something useful at least!
