### ISSUE TITLE
Everything is tagged as "new" 

### ISSUE THREAD

**Issue by AndrewBreyen** [arantius/zap2xml-py#3]
Hello, when using output file in Jellyfin, everything is marked as new. 

Command ran: `/usr/local/bin/python3 /Users/macbook/zap2xml-py/zap2xml.py -z 55303`

Screenshot of Jellyfin Guide Data:
<img width="1365" alt="Screen Shot 2022-01-05 at 5 50 44 PM" src="https://user-images.githubusercontent.com/7895581/148344466-c657bbb2-096e-4778-972a-06ade003da5c.png">

Ghost Whisperer (and lots of other things) are not new, these are not listed as new on https://tvlistings.zap2it.com/

results in file: (uploaded as txt because of GitHub restrictions, but its actually an .XML file)
[xmltv.txt](https://github.com/arantius/zap2xml-py/files/7820121/xmltv.txt)

any ideas? thanks!

**Comment by arantius** [comment]
The file you attached has 12,107 <programme> tags and 2,217 <new> tags.  Looks good to me.

**Comment by AndrewBreyen** [comment]
Looks like this is a Jellyfin issue. 
https://www.reddit.com/r/jellyfin/comments/rx0kqq/comment/hrod03x/?utm_source=share&utm_medium=web2x&context=3
