### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by ZippoD** [arantius/zap2xml-py#4]
Hi there, 
Looks like this one doesn't provide and image. Any plans on adding that?
Here is an example from the still working Windows.exe script (I am not capable of scripting this my self):

<channel id="I2.1.20454.zap2it.com">
		<display-name>2.1 WBMDT</display-name>
		<display-name>2.1</display-name>
		<display-name>WBMDT</display-name>
		<icon src="https://zap2it.tmsimg.com/h3/NowShowing/20454/s28711_h3_aa.png" />
</channel>

<programme start="20220217170000 -0500" stop="20220217173000 -0600" channel="I5.2.45805.zap2it.com">
		<title lang="en">The Nanny</title>
		<sub-title lang="en">The Hanukkah Story</sub-title>
		<desc lang="en">Fran becomes convinced that Maxwell doesn&apos;t care about Hanukkah as much as Christmas; Maxwell and Grace get stranded.</desc>
		<length units="minutes">30</length>
		<icon src="https://zap2it.tmsimg.com/assets/p1659147_e_v9_aa.jpg" />
		<url>https://tvlistings.zap2it.com//overview.html?programSeriesId=SH00087591&amp;tmsId=EP000875910137</url>
		<episode-num system="common">S06E10</episode-num>
		<episode-num system="dd_progid">EP00087591.0137</episode-num>
		<episode-num system="xmltv_ns">5.9.</episode-num>
		<previously-shown />
		<subtitles type="teletext" />
	</programme>

**Comment by arantius** [comment]
No plans.  As readme says, this is "a very simple script".
